### ISSUE TITLE
uint datatype not recognized

### ISSUE THREAD

**Issue by Twistx77** [melopero/Melopero_APDS-9960_Arduino_Library#1]
Hi,

I just tried to compile your library with the latest Arduino IDE and I get the following error: 

/Arduino/libraries/Melopero_APDS9960/src/Melopero_APDS9960.h:441:25: error: 'uint' has not been declared
     int8_t parseGesture(uint parse_millis, uint8_t tolerance = 12, uint8_t der_tolerance = 6, uint8_t confidence = 6);

I tried uncommeting the #include <stdint.h> at the top of the file but it doesn't help since uint is not a standard data type.

Is this an error? I tried changing it for uint32_t but then I get the same error in different places on the cpp file. I changed it there also and now it compiles.

**Comment by leoli51** [comment]
Hi @Twistx77,

Thank you very much for your feedback!
I tried to recompile it on my system and it built with no errors. Anyway I changed the code so that the parse_millis is an uint16_t and there aren't any uint's in the code anymore. I changed the parse millis to uint16_t instead of uint32_t to prevent a possible integer overflow error that could happen if you try to parse a gesture for a long time . 
I uploaded a new version and now everything should be working.
